# Format: {folx} can have {treat}, as a treat
# UNLESS the treat uses alternate wording, in which case the format is: {folx} {treat}, as a treat

# Note: The case of these will not be changed.
FOLX = [
    "Transfems",
    "Foxgirls",
    "Foxes",
    "Transmascs",
    "Catgirls",
    "Catboys",
    "Wolfgirls",
    "Wolfboys",
    "Puppygirls",
    "Dogboys",
    "Furries",
    "Ratgirls",
    "Wyverns",
    "Deergirls",
    "Cryptids",
    "I",
    "The Maus",
    "Bees",
    "Wikipedians",
    "Mathematicians",
    "CS undergrads",
    "Rust developers",
    "Javascript developers",
    "Python developers",
    "PHP developers",
    "C developers",
    "C++ developers",
    "C# developers",
    "Java developers",
    "Arch Linux users",
    "Alpine Linux users",
    "Gentoo users",
    "Nix users",
    "Debian users",
    "Windows users",
    "Mac users",
    "Fedora users",
    "You",
    "Fedibots",
    "Robotgirls",
    "Dolls",
    "labyrinth.zone users",
    "fox.nexus users",
    "beehive.city users",
    "Yassie",
    "Yaseenists",
    "Folx that use they/them",
    "Open source maintainers",
    "Package maintainers",
    "Mastodon users",
    "Akkoma users",
    "Sharkey users",
    "Glitch-soc users",
    "GoToSocial users",
    "Firefish users",
    "Iceshrimp users",
    "Dagns",
    "Good pets",
    "Gamers",
    "Doms",
    "The Kat",
    "Polycules",
    "FFXIV players",
    "Cuties",
    "Boykissers",
    "Girlkissers",
    "Enbykissers",
    "Femboys",
    "Useless lesbians",
    "Orange cats",
    "Void kitties",
    "Everyone",
    "Nyanbinary folx",
    "Friend-shaped creatures",
    "Neurospicy people",
    "Sammy",
    "Xenia",
    "Livvy",
    "Luna",
    "Julia",
    "Kris",
    "Fuxle",
    "Cal",
    "transfem.social users",
    "Lexi",
    "catgirl-engine users",
    "Cute dorks",
    "The BOFH",
    "Wikimedians",
    "Pastafarians",
    "Discordians",
    "Neurotypicals",
    "Vim users",
    "Emacs users",
    "Nano users",
    "Large Language Models",
    "Lost robots",
    "Scientists",
    "Subscribers",
    "Software supply chains",
    "Infosec mavens",
    "Rapid response furries",
    "Robos",
    "Drones",
    "We",
    "Omegas",
    "Alphas",
    "Queer people",
    "Debian Maintainers",
    "Debian Developers, uploading",
    "Debian Developers, non-uploading",
    "Humanoids",
    "Canids",
    "Vulpines",
    "Felines",
    "Kreechurs",
    "Optimists",
    "Pessimists",
    "Realists",
    "Grouchy sysadmins",
    "Poets",
    "The Scout from TF2",
    "The Soldier from TF2",
    "The Pyro from TF2",
    "The Demoman from TF2",
    "The Heavy from TF2",
    "The Engineer from TF2",
    "The Medic from TF2",
    "The Sniper from TF2",
    "The Spy from TF2",
    "Demoknight mains",
    "We and our 847 partners",
    "Xbox players",
    "Playstation players",
    "PC players",
    "Nintendo players",
    "Dani",
    "Mara",
    "Rail",
    "Taavi",
    "Herobrine",
    "Sackboy",
    "Robloxians",
    "Everyone in the closet",
    "Disabled people",
    "That kind person at the grocery store",
    "Critters",
    "Non-human entities",
    "Therians",
    "No one",
    "Nerds",
    "Dorks",
    "Cat lovers",
    "Dog lovers",
    "Gardeners",
    "Claire",
    "A random MediaWiki extension",
    "A random MediaWiki skin",
    "MediaWiki",
    "Skin:Citizen",
    "Extension:Cargo",
    "Miraheze",
    "Starfleet captains",
    "Klingons",
    "Romulans",
    "Vulcans",
    "Ferengi",
    "The Borg",
    "Soong-type androids",
    "Extension:DataDump",
    "Extension:CSS",
    "Extension:CreateWiki",
    "Extension:WikiDiscover",
    "Neocats",
    "Neofoxes",
    "Cheese gobblers",
    "Disney adults",
    "IRC users",
    "ChanServ",
    "NickServ",
    "API crime committers",
    "gts.apicrim.es users",
    "Dragonfoxes",
    "Yinglets",
    "My (25M) subs (23F, 26F, 22M, 28M, 28M)",
    "Slenderman",
    "K&R",
    "Vampires",
    "D&D players",
    "The DM",
    "Madeline",
    "Part of You",
    "Readers",
    "The ouroboros",
    "Fedi users",
    "New fedi users",
    "Elf-friends",
    "Chell",
    "GLaDOS",
    "Wheatley",
    "The BDFL",
    "Lucas",
    "Hobbits",
    "Fedi meta",
    "Medi feta",
    "The Steam catgirl",
    "XMPP users",
    "Hackers",
    "OpenStreetMap contributors",
    "Discordian popes",
    "Chat",
    "Moths",
    "Grown-ups",
    "People who work from home",
    "The bots",
    "That one",
    "Blåhajar",
    "liv",
    "Your Innie",
    "Your Outie",
    "The Smol",
    "Hackerspaces",
    "Beepers",
    "Computer touchers",
    "SCP-085",
    "Bouba",
    "Kiki",
    "Monsterdon",
    "As a Treat bot contributors",
    "GPN attendees",
    "OpenStack Swift administrators",
    "catgirls of the .[center|cloud|global] variety",
    "Blue",
    "Jade",
    "The treats bot",
    "NTSC video",
    "Kittens",
    "Spherical cow in a vacuum",
    "Ducks",
    "Quackers",
    "Girls",
    "Boys",
    "Enbies",
    "Dragons",
    "39C3 attendees",
    "The Crystalline Entity",
    "The Arsons",
    "The Arson family",
    "The hiders",
    "The seekers",
    "People who've seen it",
    "People who've seen it and said it",
    "Cats",
    "Typst users",
    "LaTeX users",
    "Mr Barrister John Warosa",
    "$instance$HOST$ users",
    "Eve Entropia",
    "Fea",
    "The board of Chaostreff Backnang",
    "Canadians",
    "Helix users",
    "The queerbox",
    "The S-Bahn Stuttgart",
    "MaSzyna players",
    "Zoey",
    "Lilian",
    "Abby",
    "The U.S. Chemical Safety Board",
    "Objects that struck the data center",
    "The wolp",
    "Baby Globe",
    "The gostak",
    "RimWorld players",
    "Chloë",
    "Eridians",
    "Viltrumites",
    "Backstage managers",
    "Backstage damagers",
    "Raine",
    "Chippy thieves",
    "Users in the sudoers file",
    "The goose",
    "Moopsy",
    "Riley",
    "Sisyphus",
    "The two wolves inside you",
    "We&",
    "Simor Haskiner",
]

# Note: The case of these will not be changed.
# either give a string or a JSON object
# with "text" and "alt_wording" keys
TREATS = [
    '{"content_warning": "lewd", "text": "steaming hot lesbian sex"}',
]
